language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
    pip install coveralls
#"pip install -r requirements.txt"
# command to run tests
script:
  - coverage run --source=. tests.py
  - coverage report -m
#nosetests
after_script:
    coveralls --verbose
